"""Command line entry point: runs the P1.2 viewer on the DEMO / MOCK provider.

To visualise real simulation data, do not edit this file's logic; build a
provider from P1.1 (see README, "Connecting P1.1") and pass it to
``psamathe_p12.viewer.run_viewer``.
"""

from __future__ import annotations

import argparse
from typing import Optional, Sequence

from .config import MAX_TRAJECTORY_HISTORY, RepresentationConfig
from .mock_provider import MOCK_LABEL, MockConfig, MockStateProvider


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="python -m psamathe_p12",
        description=f"Psamathe P1.2 visualization running on the {MOCK_LABEL} (not the real simulator).",
    )
    g = p.add_argument_group("mock data source (demo only)")
    g.add_argument("--particles", type=int, default=8, help="number of demo particles incl. central body (default 8)")
    g.add_argument("--seed", type=int, default=42, help="deterministic seed (default 42)")
    g.add_argument("--dt", type=float, default=0.02, help="simulation time per mock snapshot (default 0.02)")
    g.add_argument("--max-steps", type=int, default=None, help="end the mock stream after N snapshots")

    g = p.add_argument_group("representation")
    g.add_argument("--history", type=int, default=300,
                   help=f"trajectory points kept per particle, 0-{MAX_TRAJECTORY_HISTORY} (default 300)")
    g.add_argument("--velocity-scale", type=float, default=None,
                   help="display length per unit velocity (default: automatic)")
    g.add_argument("--show-forces", action="store_true", help="draw force arrows where the source provides forces")
    g.add_argument("--no-trajectories", action="store_true")
    g.add_argument("--no-velocity", action="store_true")
    g.add_argument("--no-ids", action="store_true")
    g.add_argument("--axis-mode", choices=["expand", "fit"], default="expand",
                   help="expand: axes only grow (stable); fit: axes follow the data")

    g = p.add_argument_group("run mode")
    g.add_argument("--interval", type=int, default=40, help="milliseconds between frames (default 40)")
    g.add_argument("--frames", type=int, default=None,
                   help="number of snapshots to consume (default: endless live, 300 when saving)")
    g.add_argument("--save", metavar="PATH", default=None,
                   help="render headless to PATH (.png = final frame, .gif = animation) instead of opening a window")
    return p


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        mock_cfg = MockConfig(n_particles=args.particles, seed=args.seed, timestep=args.dt, max_steps=args.max_steps)
        rep_cfg = RepresentationConfig(
            trajectory_history_length=args.history,
            show_trajectories=not args.no_trajectories,
            show_velocity_vectors=not args.no_velocity,
            show_particle_ids=not args.no_ids,
            show_forces=args.show_forces,
            velocity_scale=args.velocity_scale,
            axis_mode=args.axis_mode,
        )
    except ValueError as exc:
        build_parser().error(str(exc))

    provider = MockStateProvider(mock_cfg)

    if args.save:
        import matplotlib
        matplotlib.use("Agg")  # headless; must happen before pyplot is imported
        from .viewer import render_to_file
        rep = render_to_file(provider, rep_cfg, args.save, frames=args.frames or 300)
        print(f"Saved {args.save} ({rep.snapshots_received} snapshots consumed from {MOCK_LABEL}).")
    else:
        from .viewer import run_viewer
        run_viewer(provider, rep_cfg, interval_ms=args.interval, frames=args.frames)
    return 0
